name: Test nightly

on:
  schedule:
    - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  test-nightly:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose --features 'nightly' -- --show-output --include-ignored
